### ISSUE TITLE
Unable to fetch data tracks in the embedded browser

### ISSUE THREAD

**Issue by ericaenjoy3** [lidaof/eg-react#170]
Hi,

I downloaded the example html (http://target.wustl.edu/dli/eg/embed.html) of the embedded browser, and the last three bigWig data tracks failed to be fetched, when opened locally. Would you know why it does not work?

And an aesthetic question -- where in the example html file would you recommend modifying so as to remove the gap on the right hand side between the WashU browser and the edge of the browser display?

Many thanks!

**Comment by lidaof** [comment]
Hi @ericaenjoy3 it's working on my side..can you take a screenshot? (better with the web console, there maybe error messages)
![image](https://user-images.githubusercontent.com/102806/89336278-c34b8e00-d65e-11ea-9831-fdf76c5adda4.png)

the `div` element which is the container for the browser has a fixed size of 1000px, you can try increase it, or set width to 100% etc..

**Comment by ericaenjoy3** [comment]
Hi @lidaof, I downloaded and opened the html file locally, and the error messages are shown below. Thanks!

![Screenshot from 2020-08-05 00-42-00](https://user-images.githubusercontent.com/6052159/89376485-df324c80-d6bd-11ea-8c20-a482c991edfd.png)
![Screenshot from 2020-08-05 00-42-34](https://user-images.githubusercontent.com/6052159/89376489-e22d3d00-d6bd-11ea-9d86-97488c9d7866.png)
![Screenshot from 2020-08-05 00-43-01](https://user-images.githubusercontent.com/6052159/89376498-e5282d80-d6bd-11ea-9cca-d106aff9d3e2.png)

**Comment by lidaof** [comment]
Hi @ericaenjoy3 , i see, that won't work. You can use a very easy to use http server to host the html and js files: https://www.npmjs.com/package/http-server

**Comment by ericaenjoy3** [comment]
Hi @lidaof, I have uploaded the html file alone to an http server, and the bigWig data track fetch also failed. As you mentioned js files, are these provided by https://www.npmjs.com/package/http-server or somewhere else? Many thanks.

![Screenshot from 2020-08-05 15-56-51](https://user-images.githubusercontent.com/6052159/89458533-2ad40d00-d735-11ea-85fe-b40b87553be3.png)

**Comment by lidaof** [comment]
Hi @ericaenjoy3 you can download http://target.wustl.edu/dli/eg/epgg.js and http://target.wustl.edu/dli/eg/epgg.css and put them at the same folder with the embedding.html, that should fix the problem.

**Comment by ericaenjoy3** [comment]
Hi @lidaof, I downloaded these two js files to the same folder (https://liuy22.u.hpc.mssm.edu/epgg.js and https://liuy22.u.hpc.mssm.edu/epgg.css) as the embedding.html file, and the problem of data track retrieval with https://liuy22.u.hpc.mssm.edu/embedding.html still persist. Would you please care to look into this? Much appreciated.

**Comment by lidaof** [comment]
you changed many paths to the JS files the page need, you don't need change them. you need the original embedding.html, epgg.js, epgg.css files in same directory and it should work. Or if you put them in local folder, you need point their path correctly.. you can go to http://target.wustl.edu/dli/eg/embed.html, right click, view page source, copy all html and replace your current html file.  is it clear?

![image](https://user-images.githubusercontent.com/102806/89573804-cbd3ce00-d7f0-11ea-8458-aa7514dfb75f.png)

**Comment by ericaenjoy3** [comment]
Hi @lidaof, I actually didn't modify the 'embedding.html' at all upon downloading from the source, and I presume these errors were generated because these are relative file paths coded in the html file. 

I downloaded the 'embed.html' from the source to the http server at my end, and as you could see, the problem persisted (https://liuy22.u.hpc.mssm.edu/embed.html).

**Comment by lidaof** [comment]
I see...sorry for that. can you go to http://target.wustl.edu/dli/eg/ and download the *.worker.js and put them at same folder. Thank you!

**Comment by ericaenjoy3** [comment]
Hi @lidaof, that's awesome! First two bigwig tracks of data are loaded through https://liuy22.u.hpc.mssm.edu/embed.html, but the last track is still problematic. Any other js files are missing for the third track to be loaded? Thanks!

**Comment by lidaof** [comment]
my bad...can you make a folder named `js` and put this file http://target.wustl.edu/dli/eg/js/zlib_and_gzip.min.js under it. this should fix it.

**Comment by ericaenjoy3** [comment]
@lidaof, great! That works! Many thanks!
