### ISSUE TITLE
Issue with WashU browser

### ISSUE THREAD

**Issue by vivekliai** [lidaof/eg-react#75]
When running the latest WashU browser (http://epigenomegateway.wustl.edu/browser/), I can not upload / visualize any tracks. I am facing the following issues:
1) When manually uploading a .json file (tracks -> add custom data hub -> upload data hub file), the server is unresponsive.
2) Specifying http link of .json file (tracks -> add custom data hub -> load datahub url) produces errors like http 0 / http 401
3) Uploading tracks individually (tracks -> add custom track) through web links: does not pull and display data for the track. Shows an error "data fetch failed".

WashU documentation suggests enabling CORS in host web server, which I do not understand.
https://epigenomegateway.readthedocs.io/en/latest/tracks.html#configure-your-webserver-to-enable-cors

**Comment by lidaof** [comment]
Hi @vivekliai , thanks for using the browser.

1 and 2 should be working, would you mind send me your data hub URL or track URL?

for 3, the new browser uses Javascript code to access files from different domain, that's the reason we ask users to enable CORS, do you have a web server setup? which OS and software are you using?

Thanks.

**Comment by vivekliai** [comment]
Hi Daofeng,

It is giving us problem with all tracks we have. Here one of them:

https://informaticsdata.liai.org/BioAdHoc/Groups/vd-vijay/sourya/DATA/HiChIP/Mumbach_2017_paper/Session_Details/GM_H3K27ac_HiChIP_WashUSession.json <https://informaticsdata.liai.org/BioAdHoc/Groups/vd-vijay/sourya/DATA/HiChIP/Mumbach_2017_paper/Session_Details/GM_H3K27ac_HiChIP_WashUSession.json>


We have web server setup that uses linux Redhat. Our computer is Mac.

Let us know if you need more information
Thanks for your help,
Vivek





Vivek Chandra, Ph.D.
Division of Vaccine Discovery
La Jolla Institute for Allergy and Immunology
9420 Athena Circle
La Jolla, CA 92037, USA

**Comment by lidaof** [comment]
Hi @vivekliai , i see you link need a password to access?

have you tried use https://username:password@your.website this syntax of URL? 
(I actually haven't tried that)

![image](https://user-images.githubusercontent.com/102806/50184899-fb605a80-02db-11e9-939b-4fb7df9773ce.png)

**Comment by vivekliai** [comment]
Hi Daofeng,

Thanks for your reply. We have tried providing username and password in both .json file link as well as on individual tracks. The same problem persists.
Please use the attached text file containing list of tracks. You may use it as a complete .json file or may load individual tracks.
Please check and let us know for any further information. 






Vivek Chandra, Ph.D.
Division of Vaccine Discovery
La Jolla Institute for Allergy and Immunology
9420 Athena Circle
La Jolla, CA 92037, USA

**Comment by lidaof** [comment]
Hi @vivekliai , I am guessing our data fetching code might not working with password URL...
do you need help on host data on our server? I can give you an random URL for that.

**Comment by vivekliai** [comment]
Hi Daofeng,

Thanks for your reply. Let us discuss with our PI’s about loading data on your server, and we’ll get back to you.

We used the old (legacy) version of WashU. Unfortunately for last few days, the legacy version is also not working properly. Tracks are arbitrarily not loaded, or sometimes partially loaded (ChIP-peaks or Hi-C contacts are randomly missing). So, it would be nice if you check the legacy browser with the same .json file we have provided, and ensure if all tracks can be uploaded properly. We are happy if the legacy browser works properly. 


Vivek Chandra, Ph.D.
Division of Vaccine Discovery
La Jolla Institute for Allergy and Immunology
9420 Athena Circle
La Jolla, CA 92037, USA

**Comment by lidaof** [comment]
Hi @vivekliai , did you say the same JSON used work with old browser without username or password? Thanks.

**Comment by vivekliai** [comment]
Hi Diofeng,

Thanks. For old browser we used to work with saved tracks. After that we made JASON file for legacy version and it is working without password for that. The major problem we are facing with legacy version is that it works good for few days and suddenly it starts losing or getting new peaks or contacts. And then after few days it becomes normal. We send you same JASON file that works for legacy version without username or password. 

Best,
Vivek

**Comment by lidaof** [comment]
Hi @vivekliai, i see, this probably caused by the URL changes..I did apply a fix and that should not be a problem...the file uploaded using file upload function actually were cleaned every 6 month...not sure if your uploaded file had been cleaned by our auto script. We are trying to developing the local file read function for new browser this will solve the dependency on web server. Right now the solution would be I can host the data for your data hub. (or you might need re-upload some track files, sorry for the trouble)

**Comment by lidaof** [comment]
Hi @vivekliai, you may want to try the [local file upload](https://eg.readthedocs.io/en/latest/local.html) since the browser cannot deal the password protected URLs, let me know if anything. I am closing this issue for now. Feel free to reopen it.

**Comment by jgbaum** [comment]
Hi @lidaof,

I'm trying to help @vivekliai to resolve this issue and have done a bit of testing to confirm that the issue is not related to URLs containing authentication info.  I've gone ahead and placed a bigwig file on an apache server located [here](https://downloads.iedb.org/misc/test_track.bigWig).

That server (CentOS 7) has been configured with CORS support, according to the [instructions provided by WashU](https://epigenomegateway.readthedocs.io/en/latest/tracks.html).  I've verified that CORS is working at test-cors.org [here](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fdownloads.iedb.org%2Fmisc%2Ftest_track.bigWig&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

However, I've been unable to get the track to load in the new genome browser.  Here is a screenshot of the javascript console error that I'm getting:

![image](https://user-images.githubusercontent.com/6494933/52022743-23340800-24af-11e9-8071-bda31448a6c6.png)

If I take one of the range URLs mentioned in the console logs and try to pull it via wget (from a different domain), it pulls without error:

![image](https://user-images.githubusercontent.com/6494933/52022858-9473bb00-24af-11e9-985c-b6935f2f9b93.png)

I've even gone a step further and configured a separate Ubuntu system to serve the files via apache (as your instructions mention Ubuntu specifically), but the same behavior is observed.

So I'm at a point where I can use your input regarding what settings changes we might be able to make or any other advice you can offer to get the track to load properly via a URL, as uploading the tracks is not a long-term, sustainable option for us.

Note that this track loads just fine in the legacy genome browser, whether hosted on informaticsdata.liai.org or downloads.iedb.org, both with and without authentication information in the URL.

Please let me know if there's any other information I can provide to help resolve this issue.  Your assistance is greatly appreciated1

Thanks,

J
